<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magmodules\MessageBird\Block\ProductAlert\Stock;
use Magmodules\MessageBird\Block\ProductAlert\Price;
?>
<?php /* @var $block Stock|Price */?>
<div class="product alert <?= $block->escapeHtml($block->getType())?>">
    <a href="javascript:void(0);"
       title="<?= $block->escapeHtml(__($block->getSignupLabel())) ?>"
       class="messagebird-alert-<?=$block->escapeHtml($block->getType())?> action alert">
        <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
    </a>
</div>
<script type="text/x-magento-init">
        {
            "*": {
                "Magmodules_MessageBird/js/product-alert": {
                    "AjaxUrl": "<?= $block->escapeUrl($block->getSignupUrl()); ?>",
                    "type": "<?= $block->escapeHtml($block->getType())?>"
                }
            }
        }
</script>
