<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magmodules\MessageBird\Block\Adminhtml\System\Config\Button\Credentials;

/**
 * @see \Magmodules\MessageBird\Block\Adminhtml\System\Config\Button\Credentials
 * @var Credentials $block
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var resultSpan = jQuery('#result_api');
        jQuery('#messagebird-button_credentials').click(function () {
            var params = {
                "api_key_test": jQuery("input[name='groups[general][fields][api_key_test][value]']").val(),
                "api_key_live": jQuery("input[name='groups[general][fields][api_key_live][value]']").val(),
                "originator": jQuery("input[name='groups[general][fields][originator][value]']").val(),
                "test_mode": jQuery("select[name='groups[general][fields][test_mode][value]']").val()
            };
            new Ajax.Request('<?= $block->escapeUrl($block->getApiCheckUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    resultSpan.find('.connecting').hide();
                    resultSpan.find('.result').show();
                    resultSpan.find('.result').html(response.responseText);
                }
            });
        });
    });
</script>
<?= $block->getButtonHtml() ?>
<div id="result_api">
    <span class="connecting" style="display: none;">Connecting...</span>
    <span class="result"></span>
</div>
