<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magmodules\MessageBird\Block\Adminhtml\System\Config\Button\Credentials;

/**
 * @see \Magmodules\MessageBird\Block\Adminhtml\System\Config\Button\Credentials
 * @var Credentials $block
 */
?>

<div class="mm-ui-credentials">
    <div class="mm-ui-action">
        <?= $block->getButtonHtml() ?>
        <span class="mm-ui-connecting" style="display: none;">
            <?= $block->escapeHtml(__('Connecting...')); ?>
        </span>
    </div>

    <div class="mm-ui-result"></div>
</div>

<script>
    require(['jquery'], function($) {
        const button = $('#mm-ui-button_credentials');
        const result = $('.mm-ui-result');
        const loader = $('.mm-ui-connecting');
        const requestUrl = '<?= $block->escapeUrl($block->getApiCheckUrl()) ?>';

        button.click(() => {
            const params = {
                "api_key_test": $('input[name*=api_key_test]').val(),
                "api_key_live": $('input[name*=api_key_live]').val(),
                "originator": $('input[name*=originator]').val(),
                "test_mode": $('select[name*=test_mode]').val()
            };

            new Ajax.Request(requestUrl, {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate() {
                    loader.show();
                    result.hide();
                },
                onSuccess(response) {
                    loader.hide();
                    result.show().html(response.responseText);
                }
            });
        });
    });
</script>
